### ISSUE TITLE
V4 does not log anything in react-native even when not in production

### ISSUE THREAD

**Issue by matthieugicquel** [TanStack/query#4017]
### Describe the bug

When using react-query v4 with react-native, nothing is logged to the console, even when during development.

For instance when a query function throws an error, the error is not logged.

### Your minimal, reproducible example

https://snack.expo.dev/@matthieugc/react-query-v4-no-logs-repro

### Steps to reproduce

Have a query that throws an error

### Expected behavior

Expected: the error is logged by react-query
Happening: nothing is logged

### How often does this bug happen?

Every time

### Platform

- React Native 0.69.3

### react-query version

4.0.10

### Additional context

Here's why this seems to be happenning:

The package.json for react-query (and query-core) v4 contains these fields:

https://github.com/TanStack/query/blob/1d9c2120ce0bcee95a047e90dbaee66f56b01646/packages/react-query/package.json#L13-L15

https://github.com/TanStack/query/blob/1d9c2120ce0bcee95a047e90dbaee66f56b01646/packages/query-core/package.json#L13-L15

And metro, the react-native bundler, [uses the `browser` field in priority when it's available](https://facebook.github.io/metro/docs/configuration/#resolvermainfields)

→ For react-query, it points to the UMD production build, where the default logger calls have been removed during bundling

**Comment by TkDodo** [comment]
thanks for the analysis. @DamianOsipiuk is this another thing for our bundling changes? I know you mentioned that we should remove the `main` field altogether ?

**Comment by DamianOsipiuk** [comment]
Yeah. I think that many bundlers prefer `browser` field when available (webpack docs). And it should not be an UMD build, but browser specific build. IE. That does not contain any node specific code.
So i think we need to remove it so those bundlers will fall back to other entries.
I will be able to do that begining of next week, unless someone else makes that so we could do another pre-release.

**Comment by vanniewelt** [comment]
Same problem here, except with React JS.

**Comment by DamianOsipiuk** [comment]
@matthieugicquel could you check if problem persists in https://github.com/TanStack/query/releases/tag/v4.0.11-beta.5?

**Comment by matthieugicquel** [comment]
@DamianOsipiuk The logging problem is fixed in this release, thanks!

(Note for other people who may try to install it: I had to manually install the right version of query-core since it would resolve to 4.2.1 instead of the beta version)

By the way I noticed that the `.native` files in the codebase are still not getting included, which is logical since react-query come already bundled.

For instance [the logger file](https://github.com/TanStack/query/blob/v4.0.11-beta.5/packages/query-core/src/logger.native.ts) is not used. I'm not sure this one is needed anymore since recent versions of react-native (or expo, not sure) don't have the fullscreen red box that justified it.

But maybe not having [the one for batchedUpdates](https://github.com/TanStack/query/blob/v4.0.11-beta.5/packages/react-query/src/reactBatchedUpdates.native.ts) will cause issues?

**Comment by TkDodo** [comment]
> (Note for other people who may try to install it: I had to manually install the right version of query-core since it would resolve to 4.2.1 instead of the beta version)

yeah I fixed the release script, but it still depends on version with `^`, so:

```
"@tanstack/query-core": "^4.0.11-beta.5",
```

and `4.2.1` does satisfy that. I think I'll change this again to depend on strict versions, so that downgrading is also possible. Thanks for pointing that out.

**Comment by vanniewelt** [comment]
I tried to install `^4.0.11-beta.5` in React JS (I'm using React 18.2.0 & Next 12.2.5) and still don't get any logs in development mode. Devtools are showing up though. Perhaps its not even related with the React Native problem. Should I create a new issue?

**Comment by TkDodo** [comment]
@vanniewelt can you show this in a codesandbox reproduction please?

**Comment by DamianOsipiuk** [comment]
> By the way I noticed that the .native files in the codebase are still not getting included, which is logical since react-query come already bundled.

Did it work previously? How was it attached at build time? @TkDodo 

> I tried to install ^4.0.11-beta.5 in React JS (I'm using React 18.2.0 & Next 12.2.5) and still don't get any logs in development mode. Devtools are showing up though. Perhaps its not even related with the React Native problem. Should I create a new issue?

Make sure you also manually specify 
`"@tanstack/query-core": "^4.0.11-beta.5",`
Cause newer version is available and it installs the newest one.

**Comment by vanniewelt** [comment]
> @vanniewelt can you show this in a codesandbox reproduction please?

@TkDodo Unfortunately, I wasn't able to reproduce this in codesandbox with simple react app. However, I created demo repository with Next.js: https://github.com/vanniewelt/react-query-no-logging-error-demo

> Make sure you also manually specify
> `"@tanstack/query-core": "^4.0.11-beta.5",`
> Cause newer version is available and it installs the newest one.

@DamianOsipiuk I tried it and no luck

**Comment by DamianOsipiuk** [comment]
I think the issue lies here:

![image](https://user-images.githubusercontent.com/28151934/185609879-8d7f0fa1-fd68-4ea0-bbf0-908a57718985.png)

So it's due to `react-query` having a dep on `4.2.1` due to `^`

@TkDodo

**Comment by TkDodo** [comment]
> Did it work previously? How was it attached at build time? @TkDodo

I do not know, but this seems to be a separate issue. Can we move it out of this discussion please?

> "@tanstack/query-core": "^4.0.11-beta.5",

You actually have to specify exact versions. This beta thing is tricky because we have already released 4.2.1, and if you say you want something that is "compatible with 4.0.11-beta.5", you will still get `4.2.1`, because it's "larger than" the beta and it thus satisfies the constraint.

you can easily see that by inspecting node_modules. This will all go away once we release the beta.

> @TkDodo Unfortunately, I wasn't able to reproduce this in codesandbox with simple react app. However, I created demo repository with Next.js: https://github.com/vanniewelt/react-query-no-logging-error-demo

This is also the problem with your repo because you don't have strict versions specified. If I pin the versions in you repo, error logs work in dev mode:

![Screenshot 2022-08-19 at 13 37 32](https://user-images.githubusercontent.com/1021430/185610296-e666440d-c11b-4d8a-97e7-8fe2175f3248.png)

I would consider this issue done as soon as we release the beta.

**Comment by TkDodo** [comment]
@DamianOsipiuk we can release a new beta with the fixed release script if you think it matters? It should have strict versions as dependencies.

**Comment by DamianOsipiuk** [comment]
@TkDodo Yes, we can also bump the version of beta tag forcefully via actions menu to be greater than current main version.
Whatever works for you.

**Comment by TkDodo** [comment]
okay, `v4.3.0-beta.0` incoming

**Comment by vanniewelt** [comment]
@TkDodo Ah I see, thanks for explanation.

After upgrading to `v4.3.0-beta.0` it works! So we can probably close the issue.
