### ISSUE TITLE
Unable to install vue-query for nuxt 3

### ISSUE THREAD

**Issue by dextersiah** [TanStack/query#5115]
### Describe the bug

Hi folks, I am trying to experiment vue-query with Nuxt3 however when I'm trying to install the package via npm. I got an error regarding conflicting peer dependency. 

However it seems to be installing right in the stackblitz environment.

![image](https://user-images.githubusercontent.com/46256927/224472622-4ec26a23-2915-438b-bac0-03882e7e1021.png)

### Your minimal, reproducible example

https://stackblitz.com/edit/nuxt-starter-vgim69?file=package.json

### Steps to reproduce

1. Create a new Nuxt3 project with `npx nuxi@latest init my-app`
2. Install vue-query `npm i @tanstack/vue-query`
3. Error installing package

### Expected behavior

There shouldn't be a dependency peer issue as I'm installing the latest Nuxt3 Version 

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/46256927/224473047-7ff6852b-a806-4b91-8400-d39378fea341.png)

### Platform

- Operation System: Windows 11
- Node Version :v16.14.0
- NPM Version: 8.3.1
- Nuxt: ^3.2.3

### Tanstack Query adapter

None

### TanStack Query version

^4.26.1

**Comment by dextersiah** [comment]
Indeed it seems like a cache issue. Fixed with the cache clean command. thanks @ctholho. Mark as answered

**Comment by kendallroth** [comment]
I am running into the same issue, with a fresh install of Nuxt 3. Cleaning the cache unfortunately did not resolve the issue, and I have verified that Vue 2.6 is not required anywhere.

- `vue@3.2.47`
- `nuxt@3.3.2`

```
❯ npm install @tanstack/vue-query
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: nuxt-app@undefined
npm ERR! Found: vue@3.2.47
npm ERR! node_modules/vue
npm ERR!   peer vue@"^3.2.47" from @nuxt/vite-builder@3.3.2
npm ERR!   node_modules/@nuxt/vite-builder
npm ERR!     @nuxt/vite-builder@"3.3.2" from nuxt@3.3.2
npm ERR!     node_modules/nuxt
npm ERR!       dev nuxt@"^3.3.2" from the root project
npm ERR!   peer vue@">=2.7 || >=3" from @unhead/vue@1.1.25
npm ERR!   node_modules/@unhead/vue
npm ERR!     @unhead/vue@"^1.1.23" from nuxt@3.3.2
npm ERR!     node_modules/nuxt
npm ERR!       dev nuxt@"^3.3.2" from the root project
npm ERR!   8 more (@vitejs/plugin-vue, @vitejs/plugin-vue-jsx, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! @tanstack/vue-query@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: vue@2.6.14
npm ERR! node_modules/vue
npm ERR!   peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.1
npm ERR!   node_modules/@vue/composition-api
npm ERR!     peerOptional @vue/composition-api@"^1.1.2" from @tanstack/vue-query@4.27.0
npm ERR!     node_modules/@tanstack/vue-query
npm ERR!       @tanstack/vue-query@"*" from the root project
```

**Comment by pastinepolenta** [comment]
Recent NPM version install peer dependencies by default. `@tanstack/vue-query` has a peer dependency @vue/composition-api@"^1.1.2" which in turn has a peer dependency `vue@">= 2.5 < 2.7"` which does not match with the goal of using Vue 3 instead of 2.

Is the peer dependencies config of those packages correct ? Or am I missing something?

**Comment by ctholho** [comment]
@pastinepolenta @vue/composition-api is marked as optional

https://github.com/TanStack/query/blob/5335294c671d58adb78a283c37bae012d03412e8/packages/vue-query/package.json#L56-L58

Optional peer dependencies shouldn't be installed: See https://github.com/npm/rfcs/issues/221

The repro stackblitz of OP doesn't have the problem you're describing.
