### ISSUE TITLE
Devtools crashes under TrustedTypes

### ISSUE THREAD

**Issue by Jack-Works** [TanStack/query#5417]
### Describe the bug

Crash

<img width="1230" alt="image" src="https://github.com/TanStack/query/assets/5390719/6372d496-b2b3-4090-bdc4-422f99f2936e">

### Your minimal, reproducible example

N/A

### Steps to reproduce

Add a TrustedType policy before rendering the devtool.

### Expected behavior

Do not use `dangerouslySetInnerHTML`.

https://github.com/TanStack/query/blob/fd02255066ac3a136f6b62863387c486d0d560fc/packages/react-query-devtools/src/devtools.tsx#L532

I see a `nonce` option but we cannot change the CSP header to do that. The HTML rendered can be static if you use CSS variables to replace them, or you can use CSSOM to insert CSS rules manually too`SheetElement.sheet`

### How often does this bug happen?

Every time

### Platform

Chrome

### Tanstack Query adapter

None

### TanStack Query version

4.29.7

**Comment by TkDodo** [comment]
can you try with v5 please, we have new devtools there

**Comment by TkDodo** [comment]
@Jack-Works have you tried the devtools in v5 ?

**Comment by Jack-Works** [comment]
> @Jack-Works have you tried the devtools in v5 ?

can I use it with react-query v4?

**Comment by TkDodo** [comment]
> can I use it with react-query v4?

no

**Comment by TkDodo** [comment]
I think this is fixed in v5.

**Comment by Jack-Works** [comment]
<img width="1405" alt="img" src="https://github.com/TanStack/query/assets/5390719/5f22f375-8b8b-4e9f-b2f2-d23d67d5575e">

hello @TkDodo I think this is not fixed in v5. A transitive dependency `node_modules/.pnpm/goober@2.1.13_csstype@3.1.2/node_modules/goober/dist/goober.modern.js` does not work with trustedTypes.

<img width="1306" alt="img" src="https://github.com/TanStack/query/assets/5390719/138807fb-5a0c-4e38-9c42-00ef62a34f6c">

**Comment by TkDodo** [comment]
can you show a reproduction please

**Comment by Jack-Works** [comment]
> can you show a reproduction please

Yes! By adding this to the HTML you can reproduce this. (Note only Chrome supports Trusted Types for now)

```html
<meta http-equiv="Content-Security-Policy" content="require-trusted-types-for 'script'">
```

If you need a playground, https://stackblitz.com/edit/github-vbuic1?file=index.html (a fork of react-query playground https://stackblitz.com/github/TanStack/query/tree/main/examples/react/simple with only the addition HTML above)

**Comment by TkDodo** [comment]
thanks for the reproduction @Jack-Works . How do we fix it?

**Comment by TkDodo** [comment]
@ardeora fyi

**Comment by TkDodo** [comment]
this hasn't been worked on for quite some months. If someone wants to work on this, I can re-open it. Otherwise, we'll just accept it as a known limitation
