### ISSUE TITLE
[solid-query] Using data in a show causes double-rendering after a transition

### ISSUE THREAD

**Issue by Brendonovich** [TanStack/query#7036]
### Describe the bug

This might be a bug in Solid itself, but when passing a query's data to a `<Show>` with a function child, the child gets ran multiple times without being cleaned up properly, resulting in the child being rendered twice. This requires that the component be mounted during a transition.

### Your minimal, reproducible example

https://stackblitz.com/edit/solidjs-templates-ydv3gm?file=src%2FApp.tsx

### Steps to reproduce

1. Load the stackblitz
2. Click the 'two' link to navigate to `/two`
3. Once the transition is complete, there are 2 breadcrumbs rendered via a portal within the `<Show>` rather than just one
4. Navigate back to `/`, reload the page, and repeat after commenting out the TSQ `Page2` in favour of the raw resource
5. Observe only one breadcrumb being rendered

### Expected behavior

I'd expect only one breadcrumb to be rendered at all times.

### How often does this bug happen?

Every time

### Platform

- OS: macOS
- Browser: Brave
- Version: 1.63.162

### Tanstack Query adapter

solid-query

### TanStack Query version

5.25.0

### Additional context

@ardeora since this is a solid problem.
Again, it's entirely possible this is a bug in Solid since there's no reason that `<Show>` should forget to cleanup, whether rendered during a transition or not.
Also it could be to do with the combination of Show + transition + Portal + TSQ

**Comment by ardeora** [comment]
This issue has now been fixed in v5.30.0. Repro here! https://stackblitz.com/edit/solidjs-templates-ern4v6?file=src%2FApp.tsx

**Comment by marvin-j97** [comment]
I'm still getting this (or something similar) with 5.62.

Basically I have a <Guard> component that uses Solid Query to fetch a User, if it exists, it shows its children, if not it shows nothing:

```tsx
export default function Guard(props: Props): JSXElement {
  const { user } = useUserSession(); // <- uses solid query

  return (
      <Show when={user()} fallback={props.fallback}>
        {props.children}
      </Show>
  );
}
```

In another completely unrelated component I am using a Transition + Show.
When mounting and unmounting a bunch of times, the transition will get stuck in the exit state.

When I add Suspense to the Guard component, it works correctly.

It is incredibly hard to reproduce in a separate repo because there seem to be a lot of moving pieces though...
